[cluster_gen]
NumLayers = 1
Output = "clusters.zip"
NumCPUs = 8
RunTime = "24:00:00"
Email = "j.l.hobbs@leeds.ac.uk"
NumAP = 2
MolSep = 6
MinSep = 2.5
CRESTOptLevel = "normal"
CRESTMethod = "gfn2"
RDNumConf = 500