[project]
name = "moleinsert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.5",
    "rdkit>=2024.9.6",
    "scikit-learn>=1.6.1",
    "tqdm>=4.67.1",
]
